{
 "title": "Helium",
 "time": { "from": "now-14d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "hotspot",
    "label": "Hotspot ID",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.tagValues(\n    bucket: \"helium\",\n    tag: \"hotspot_name\",\n    predicate: (r) => true,\n    start: -30d,\n)\n"
   },
   { "name": "bucket", "label": "Bucket", "query": "helium" },
   {
    "name": "hotspotid",
    "label": "Hotspot ID",
    "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_hotspot\")\n  |> filter(fn: (r) => r[\"hotspot_name\"] == \"${hotspot}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> group()\n  |> distinct(column: \"hotspot_id\")"
   },
   { "name": "timezonelocal", "label": "Local Time Zone", "query": "Europe/Berlin" },
   { "name": "accountid", "label": "Account ID", "query": "123456789abcdef" },
   { "name": "setupcosts", "label": "Setup costs (hardware)", "query": "1000.00" }
  ]
 },
 "panels": [
  { "title": "Helium Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Network Stats",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_stats\")\n  |> filter(fn: (r) => r[\"_field\"] == \"challenges\")\n  //|> aggregateWindow(every: 1h, fn: sum, timeSrc: \"_start\", createEmpty: true)\n  |> difference()\n  |> timedMovingAverage(every: 10m, period: 1h)\n  |> yield(name: \"data\")\n\n"
    }
   ]
  },
  {
   "title": "Helium Price",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_price\")\n  //|> filter(fn: (r) => r[\"_field\"] == \"usd\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  //|> map(fn: (r) => ({ _value:r._value, _time:r._time, _field:r._field}))"
    }
   ]
  },
  {
   "title": "Database regularly updated",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "import \"timezone\"\noption location = timezone.location(name: \"${timezonelocal}\")\n\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"update\")\n  |> filter(fn: (r) => r[\"_field\"] == \"completed\")\n  |> aggregateWindow(every: 4h, fn: count, timeSrc: \"_stop\", createEmpty: true)\n  |> map(fn: (r) => ({ r with _value: r._value-8 }))\n  |> map(fn: (r) => ({ _value: r._value, _time:r._time, _field: \"Update frequency deviation (update every 30min)\"}))\n"
    }
   ]
  },
  { "title": "Account", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Account Balance",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_account\")\n  |> filter(fn: (r) => r[\"_field\"] == \"balance_hnt\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field: \"HNT Balance\" }))"
    },
    {
     "query": "balance = from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_account\")\n  |> filter(fn: (r) => r[\"_field\"] == \"balance_hnt\")\n  |> drop(columns:[\"_start\", \"_stop\", \"account\"])\n\ncourse_eur = from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_price\")\n  |> filter(fn: (r) => r[\"_field\"] == \"eur\")\n  |> drop(columns:[\"_start\", \"_stop\", \"source\"])\n\n//balance\n//course_eur\n//join(tables: {balance: balance, course_eur: course_eur}, on: [\"_time\"])\n\njoin(tables: {balance: balance, course_eur: course_eur}, on: [\"_time\"])\n|> map(fn: (r) => ({ _time:r._time, \"Euro Balance\":r._value_balance*r._value_course_eur }))"
    }
   ]
  },
  {
   "title": "Current Balance",
   "type": "stat",
   "gridPos": { "h": 10, "w": 2, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "panelId": 41 }
   ]
  },
  {
   "title": "Reward split (all time)",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 4, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "HNT" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_reward\")\n  |> filter(fn: (r) => r[\"_field\"] == \"reward_hnt\")\n  |> drop(columns: [\"reward_type_poc\", \"reward_type_explorer\"])\n  |> sum(column: \"_value\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field: r.hotspot_name}))\n  |> rename(columns: {_value: \"\"}) //remove _value from pie slice naming\n"
    }
   ]
  },
  {
   "title": "Account 24h Rewards",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "HNT" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_reward\")\n  |> filter(fn: (r) => r[\"_field\"] == \"reward_hnt\")\n  //|> filter(fn: (r) => r[\"hotspot_name\"] == \"${hotspot}\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field: \"24h\"}))\n"
    },
    {
     "query": "  from(bucket: \"${bucket}\")\n  |> range(start: -48h, stop: -24h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_reward\")\n  |> filter(fn: (r) => r[\"_field\"] == \"reward_hnt\")\n  //|> filter(fn: (r) => r[\"hotspot_name\"] == \"${hotspot}\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field: \"prev\"}))"
    },
    {
     "query": "  from(bucket: \"${bucket}\")\n  |> range(start: -7d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_reward\")\n  |> filter(fn: (r) => r[\"_field\"] == \"reward_hnt\")\n  //|> filter(fn: (r) => r[\"hotspot_name\"] == \"${hotspot}\")\n  |> map(fn: (r) => ({ _value:r._value / 7.0, _time:r._time, _field: \"avg(7d)\"}))"
    }
   ]
  },
  {
   "title": "Reward split (recently)",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "HNT" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: -3d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_reward\")\n  |> filter(fn: (r) => r[\"_field\"] == \"reward_hnt\")\n  |> drop(columns: [\"reward_type_poc\", \"reward_type_explorer\"])\n  |> sum(column: \"_value\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field: r.hotspot_name}))\n  |> rename(columns: {_value: \"\"}) //remove _value from pie slice naming\n"
    }
   ]
  },
  {
   "title": "Account 7d Rewards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "HNT" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: -7d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_reward\")\n  |> filter(fn: (r) => r[\"_field\"] == \"reward_hnt\")\n  //|> filter(fn: (r) => r[\"hotspot_name\"] == \"${hotspot}\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field: \"7d\"}))\n"
    },
    {
     "query": "  from(bucket: \"${bucket}\")\n  |> range(start: -14d, stop: -7d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_reward\")\n  |> filter(fn: (r) => r[\"_field\"] == \"reward_hnt\")\n  //|> filter(fn: (r) => r[\"hotspot_name\"] == \"${hotspot}\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field: \"prev\"}))"
    }
   ]
  },
  {
   "title": "Account 30d Rewards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "HNT" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_reward\")\n  |> filter(fn: (r) => r[\"_field\"] == \"reward_hnt\")\n  //|> filter(fn: (r) => r[\"hotspot_name\"] == \"${hotspot}\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field: \"30d\"}))\n"
    },
    {
     "query": "  from(bucket: \"${bucket}\")\n  |> range(start: -60d, stop: -30d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_reward\")\n  |> filter(fn: (r) => r[\"_field\"] == \"reward_hnt\")\n  //|> filter(fn: (r) => r[\"hotspot_name\"] == \"${hotspot}\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field: \"prev\"}))"
    }
   ]
  },
  {
   "title": "Daily Rewards",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "HNT" } },
   "targets": [
    {
     "query": "import \"timezone\"\noption location = timezone.location(name: \"${timezonelocal}\")\n\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_reward\")\n  |> filter(fn: (r) => r[\"_field\"] == \"reward_hnt\")\n  |> drop(columns: [\"reward_type_poc\", \"reward_type_explorer\"])\n  |> aggregateWindow(every: 1d, fn: sum, timeSrc: \"_stop\", createEmpty: true)\n  |> fill(value: 0.0)\n  |> timeShift(duration: -1s)\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field: r.hotspot_name}))\n"
    }
   ]
  },
  {
   "title": "Breaking Even",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "balance = from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_account\")\n  |> filter(fn: (r) => r[\"_field\"] == \"balance_hnt\")\n  |> drop(columns:[\"_start\", \"_stop\", \"account\"])\n\ncourse_eur = from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_price\")\n  |> filter(fn: (r) => r[\"_field\"] == \"eur\")\n  |> drop(columns: [\"_start\", \"_stop\", \"source\"])\n\n//balance\n//course_eur\n//join(tables: {balance: balance, course_eur: course_eur}, on: [\"_time\"])\n\njoin(tables: {balance: balance, course_eur: course_eur}, on: [\"_time\"])\n|> map(fn: (r) => ({ _time: r._time, euro_balance: r._value_balance*r._value_course_eur }))\n|> last(column: \"euro_balance\")\n|> map(fn: (r) => ({ euro_balance: r.euro_balance, advance: ${setupcosts} }))\n|> map(fn: (r) => ({ redeption: r.euro_balance/r.advance }))\n"
    }
   ]
  },
  {
   "title": "Hotspot \"${hotspot}\"",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "repeat": "hotspot"
  },
  {
   "title": "Daily Activity",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "import \"timezone\"\noption location = timezone.location(name: \"${timezonelocal}\")\n\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_activity\")\n  |> filter(fn: (r) => r[\"_field\"] == \"event\")\n  |> filter(fn: (r) => r[\"poc_role\"] == \"witnessed_beacon\")\n  |> filter(fn: (r) => r[\"hotspot_name\"] == \"${hotspot}\")\n  |> drop(columns: [\"poc_result\", \"beaconer\"])\n  |> aggregateWindow(every: 1d, fn: count, timeSrc: \"_stop\", createEmpty: true)\n  |> timeShift(duration: -1s)\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field: \"Witnessed Beacons\"}))"
    },
    {
     "query": "import \"timezone\"\noption location = timezone.location(name: \"${timezonelocal}\")\n\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_activity\")\n  |> filter(fn: (r) => r[\"_field\"] == \"event\")\n  |> filter(fn: (r) => r[\"poc_role\"] == \"broadcast_beacon\")\n  |> filter(fn: (r) => r[\"hotspot_name\"] == \"${hotspot}\")\n  |> drop(columns: [\"poc_result\", \"beaconer\"])\n  |> aggregateWindow(every: 1d, fn: count, timeSrc: \"_stop\", createEmpty: true)\n  |> timeShift(duration: -1s)\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field: \"Broadcast Beacons\"}))"
    },
    {
     "query": "import \"timezone\"\n\noption location = timezone.location(name: \"${timezonelocal}\")\n\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_activity\")\n  |> filter(fn: (r) => r[\"_field\"] == \"event\")\n  |> filter(fn: (r) => r[\"poc_role\"] == \"challenged_beaconer\")\n  |> filter(fn: (r) => r[\"hotspot_name\"] == \"${hotspot}\")\n  |> drop(columns: [\"poc_result\", \"beaconer\"])\n  |> aggregateWindow(every: 1d, fn: count, timeSrc: \"_stop\", createEmpty: true)\n  |> timeShift(duration: -1s)\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field: \"Challenged Beaconers\"}))"
    }
   ]
  },
  {
   "title": "Proof of Coverage Stats",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_activity\")\n  |> filter(fn: (r) => r[\"_field\"] == \"witnesses\")\n  |> filter(fn: (r) => r[\"poc_role\"] == \"broadcast_beacon\")\n  |> filter(fn: (r) => r[\"poc_result\"] == \"success\")\n  |> filter(fn: (r) => r[\"hotspot_name\"] == \"${hotspot}\")\n  |> last()\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field: \"Witnesses (last beacon)\"}))\n"
    },
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: -7d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_activity\")\n  |> filter(fn: (r) => r[\"_field\"] == \"event\")\n  |> filter(fn: (r) => r[\"poc_role\"] == \"witnessed_beacon\")\n  |> filter(fn: (r) => r[\"poc_result\"] == \"success\")\n  |> filter(fn: (r) => r[\"hotspot_name\"] == \"${hotspot}\")\n  |> group()\n  |> keep(columns: [\"beaconer\"])\n  |> distinct(column: \"beaconer\")\n  |> count()\n  |> rename(columns: {_value: \"Witnessed (beaconers -7d)\"})\n"
    },
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: -7d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_activity\")\n  |> filter(fn: (r) => r[\"_field\"] == \"event\")\n  |> filter(fn: (r) => r[\"poc_role\"] == \"witnessed_beacon\")\n  |> filter(fn: (r) => r[\"poc_result\"] == \"success\")\n  |> filter(fn: (r) => r[\"hotspot_name\"] == \"${hotspot}\")\n  |> drop(columns: [\"beaconer\"])\n  |> group()\n  |> count()\n  |> rename(columns: {_value: \"Witnessed (beacons -7d)\"})\n"
    }
   ]
  },
  {
   "title": "Challenges over last 7d",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: -7d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_activity\")\n  |> filter(fn: (r) => r[\"_field\"] == \"event\")\n  |> filter(fn: (r) => r[\"poc_role\"] == \"constructed_challenge\")\n  |> filter(fn: (r) => r[\"hotspot_name\"] == \"${hotspot}\")\n  |> drop(columns: [\"beaconer\"])\n  |> group()\n  |> count()\n  |> rename(columns: {_value: \"Constructed\"})"
    },
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: -7d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_activity\")\n  |> filter(fn: (r) => r[\"_field\"] == \"event\")\n  |> filter(fn: (r) => r[\"poc_role\"] == \"challenged_beaconer\")\n  |> filter(fn: (r) => r[\"hotspot_name\"] == \"${hotspot}\")\n  |> drop(columns: [\"beaconer\"])\n  |> group(columns: [\"poc_result\"])\n  |> count()\n  |> rename(columns: {_value: \"Challenged\"})\n"
    }
   ]
  },
  {
   "title": "24h Rewards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "HNT" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_reward\")\n  |> filter(fn: (r) => r[\"_field\"] == \"reward_hnt\")\n  |> filter(fn: (r) => r[\"hotspot_name\"] == \"${hotspot}\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field: \"24h\"}))\n"
    },
    {
     "query": "  from(bucket: \"${bucket}\")\n  |> range(start: -48h, stop: -24h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_reward\")\n  |> filter(fn: (r) => r[\"_field\"] == \"reward_hnt\")\n  |> filter(fn: (r) => r[\"hotspot_name\"] == \"${hotspot}\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field: \"prev\"}))"
    }
   ]
  },
  {
   "title": "7d Rewards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "HNT" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: -7d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_reward\")\n  |> filter(fn: (r) => r[\"_field\"] == \"reward_hnt\")\n  |> filter(fn: (r) => r[\"hotspot_name\"] == \"${hotspot}\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field: \"7d\"}))\n"
    },
    {
     "query": "  from(bucket: \"${bucket}\")\n  |> range(start: -14d, stop: -7d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_reward\")\n  |> filter(fn: (r) => r[\"_field\"] == \"reward_hnt\")\n  |> filter(fn: (r) => r[\"hotspot_name\"] == \"${hotspot}\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field: \"prev\"}))"
    }
   ]
  },
  {
   "title": "30d Rewards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "HNT" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_reward\")\n  |> filter(fn: (r) => r[\"_field\"] == \"reward_hnt\")\n  |> filter(fn: (r) => r[\"hotspot_name\"] == \"${hotspot}\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field: \"30d\"}))\n"
    },
    {
     "query": "  from(bucket: \"${bucket}\")\n  |> range(start: -60d, stop: -30d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_reward\")\n  |> filter(fn: (r) => r[\"_field\"] == \"reward_hnt\")\n  |> filter(fn: (r) => r[\"hotspot_name\"] == \"${hotspot}\")\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field: \"prev\"}))"
    }
   ]
  },
  {
   "title": "Last Events",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 15, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_activity\")\n  |> filter(fn: (r) => r[\"_field\"] == \"event\")\n  |> filter(fn: (r) => r[\"hotspot_name\"] == \"${hotspot}\")\n  |> drop(columns: [\"poc_result\", \"beaconer\"])\n  |> duplicate(column: \"_time\", as: \"last\")\n  |> keep(columns: [\"last\", \"poc_role\"])\n  "
    }
   ]
  },
  {
   "title": "Alive since",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_activity\")\n  |> filter(fn: (r) => r[\"_field\"] == \"event\")\n  |> filter(fn: (r) => r[\"hotspot_name\"] == \"${hotspot}\")\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> sort(columns: [\"_time\"])\n  |> first()\n  "
    }
   ]
  },
  {
   "title": "Reward Scale",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_hotspot\")\n  |> filter(fn: (r) => r[\"_field\"] == \"reward_scale\")\n  |> filter(fn: (r) => r[\"hotspot_name\"] == \"${hotspot}\")\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> sort(columns: [\"_time\"])\n  |> last()\n  "
    }
   ]
  },
  {
   "title": "Proof of Coverage - Witnesses",
   "type": "timeseries",
   "description": "Witnesses of challenges the hotspot was involved in. E.g. In the role of a challenger (challenged_beacon) the challenged hotspot had x witnesses. Not all roles are equally interesting but they can explain your reward development.",
   "gridPos": { "h": 18, "w": 7, "x": 8, "y": 35 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_activity\")\n  |> filter(fn: (r) => r[\"_field\"] == \"witnesses\")\n  //|> filter(fn: (r) => r[\"poc_role\"] == \"broadcast_beacon\")\n  |> filter(fn: (r) => r[\"poc_result\"] == \"success\")\n  |> filter(fn: (r) => r[\"hotspot_name\"] == \"${hotspot}\")\n  //|> map(fn: (r) => ({ _value:r._value, _time:r._time, _field: \"Beacon Witnesses\"}))\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field: \"Hotspot role: \" + r.poc_role}))\n  "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 9, "x": 15, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_hotspot\")\n  |> filter(fn: (r) => r[\"hotspot_name\"] == \"${hotspot}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> group()\n  |> distinct(column: \"hotspot_id\")"
    }
   ]
  },
  {
   "title": "Daily Rewards",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "HNT" } },
   "targets": [
    {
     "query": "import \"timezone\"\noption location = timezone.location(name: \"${timezonelocal}\")\n\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_reward\")\n  |> filter(fn: (r) => r[\"_field\"] == \"reward_hnt\")\n  |> filter(fn: (r) => r[\"hotspot_name\"] == \"${hotspot}\")\n  |> drop(columns: [\"reward_type_poc\"])\n  |> aggregateWindow(every: 1d, fn: sum, timeSrc: \"_stop\", createEmpty: true)\n  |> fill(value: 0.0)\n  |> timeShift(duration: -1s)\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field: r.reward_type_explorer}))\n"
    }
   ]
  },
  {
   "title": "Rewards (8h moving)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "HNT" } },
   "targets": [
    {
     "query": "import \"timezone\"\noption location = timezone.location(name: \"${timezonelocal}\")\n\ntimedMovingSum = (every, period, column=\"_value\", tables=<-) =>\n  tables\n    |> window(every: every, period: period)\n    |> sum(column:column)\n    |> duplicate(column: \"_stop\", as: \"_time\")\n    |> window(every: inf)\n\nfrom(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_reward\")\n  |> filter(fn: (r) => r[\"_field\"] == \"reward_hnt\")\n  |> filter(fn: (r) => r[\"hotspot_name\"] == \"${hotspot}\")\n  |> drop(columns: [\"reward_type_poc\", \"reward_type_explorer\"])\n  |> timedMovingSum(every: 1h, period: 8h)\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field: \"Reward (8h)\"}))"
    }
   ]
  },
  {
   "title": "Data Transfer",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"helium_activity\")\n  |> filter(fn: (r) => r[\"type\"] == \"data_transfer\")\n  |> filter(fn: (r) => r[\"hotspot_name\"] == \"${hotspot}\")\n  |> aggregateWindow(every: 1h, fn: sum, timeSrc: \"_start\", createEmpty: true)\n  |> fill(value: 0)"
    }
   ]
  }
 ]
}